#%RAML 1.0 DataType
type: object
description: Doctor details in the hospital system
properties:
  Name: 
    type: string
    example: "Dr.Rajesh"
  StaffID: 
    type: integer
    example: 456
  Specialty: 
    type: string
    example: "Cardiology"
  EmailID: 
    type: string
    example: "rajesh@gmail.com"
  OfficeHours: 
    type: string
    example: "10AM - 5 PM"
  Timestamp: 
    type: datetime
    example: "2024-09-17T14:45:00Z"